proj_obj = \
autogrp.o \
carve.o   \
cmd16m.o  \
cmdall.o  \
cmddos.o  \
cmdelf.o  \
cmdline.o \
cmdnov.o  \
cmdos2.o  \
cmdphar.o \
cmdqnx.o  \
cmdraw.o  \
cmdtable.o\
cmdutils.o\
dbgall.o  \
dbgcv.o   \
dbgdwarf.o\
dbginfo.o \
debug.o   \
distrib.o \
global.o  \
hash.o    \
impexp.o  \
libr.o    \
libsupp.o \
linkutil.o\
load16m.o \
loaddos.o \
loadelf.o \
loadelf2.o\
loadfile.o\
loadflat.o\
loadnov.o \
loados2.o \
loadpe.o  \
loadphar.o\
loadqnx.o \
loadraw.o \
lsymtab.o \
mapio.o   \
mem.o     \
mixcache.o\
msg.o     \
obj2supp.o\
objcalc.o \
objfree.o \
objio.o   \
objnode.o \
objomf.o  \
objorl.o  \
objpass1.o\
objpass2.o\
objstrip.o\
omfreloc.o\
orlstubs.o\
overlays.o\
ovlsupp.o \
permdata.o\
posixio.o \
procfile.o\
reloc.o   \
ring.o    \
ring2.o   \
salloc.o  \
spillio.o \
strtab.o  \
symmem.o  \
symtrace.o\
toc.o     \
virtpage.o\
wcomdef.o \
wlink.o   \
wlnkmsg.o \
dwlngen.o \
dwutils.o \
sharedio.o \
wridfree.o
